---
title: "a3_task2_Rennacker_Travis"
author: "Travis Rennacker"
format: 
  html: 
    toc: true
    code-fold: true
    code-tools: true 
    code-summary: "Show Code"
    embed-resources: true
execute:
  warning: false 
  message: false
---

```{r}
forest_fire_raw <- read_csv(here("data", "forestfires.csv"))
```



For Task 2, we’re going to recreate results from an early paper on random forests. We will tune a regression random forest that will predict the amount of forest burned given a set of climate and “spatial variables”. 

Please read the paper to get a breakdown of all the variables, analysis steps, and grouping of variables. 

Include in your knitted html a data citation and brief description of the data and variables. In the paper, you can ignore the descriptions on SVM and NN. They are other ML algorithms not covered in class. 

Import the data using read_csv(). Convert the spatial and temporal variables to factors. Log(x+1) transform the burned hectares data

Choose One of the variable groupings to build a random forest model using tidymodels.

STFWI: All features
STM: Spatial, temporal, and environmental variables
FWI: Only fire index variables 
M: Only the environmental variables

(Optional: Do each grouping and compare to a multiple regression. Try using purrr or for loops to knock it out faster)

Tune your model by selecting the best performing mtry and min_n random forests variable. Select the best performing model based on the Mean Absolute Error Metric (mae in tidymodels, called MAD in the paper). Be judicious in the number of grids to tune over! Keep it small (~12) otherwise it will take a while to render your html!

Finalize the best performing model. Then predict the outcomes on the testing data. Compare your results to those in the paper (table 3). Did tuning the random forest yield better results? Hint: You will need to transform the predictions and area values back to non-log values in order to compare to the paper. Mutate each column, then use yardstick::mae() to calculate the mae value used in the paper.

Conduct a variable importance analysis using the vip package on your final model. Which variables contribute the most to your model predictions? Do these make sense?

Create and submit a finalized HTML (rendered from .qmd) that includes: 

7.	An overview section with subsections that briefly summarize the dataset (this should include a well formatted data citation and the purpose of your analysis  Your writeup should look and feel professional in style, tone, and substance. Make it clear which groups of variables you will be analyzing.

8.	All code, including attached packages, should be included using code-folding.  Make sure to suppress any messages & warnings. Set embed-resources to be true so your HTML is self-contained!

9.	A well designed table of the results of the random forests.

10.	A graph depicting the variable importance of your selected model.

11.	A brief summary (nicely formatted and professionally written bulletpoints are fine) highlighting some major takeaways from your variable importance diagrams.

12.	Optional: Consider including a photo or image that is relevant to your analysis.  Consider applying a Bootswatch theme to your document (theme: themename in the Quarto document header)
Task 3: Shiny app term project
For this task, update your Shiny app.  Make sure to push your changes to Github!

•	Work on finalizing the Introduction/Summary/Overview page of your app

•	Update so that all widgets and reactive outputs (tables, graphs, maps, etc.) are functioning correctly

•	Start finalizing the little things (citations, formatting graphs/tables & figures), work on usability for an app user, make this nice & professional to look at 
That’s it. Nathan should be added to your app repo already, so will check progress. The idea is that by the time you submit this assignment, you should have the last two weeks to work mostly on making it awesome (adding bells & whistles, fine-tuning, theming, etc.). 




